### ISSUE TITLE
Dictionary Keys in Chapter 6 need to be converted to a list

### ISSUE THREAD

**Issue by Amanda-Clark** [nltk/nltk_book#101]
In chapter 6, section 1.3, the following code:
    word_features = all_words.keys()[:2000]
needs to be changed to
    word_features = list(all_words.keys())[:2000]
The former code gives "TypeError: 'dict_keys' object is not subscriptable" as an error message.

**Comment by ewan-klein** [comment]
Fixed in 6c04d2b
