### ISSUE TITLE
Wrong usage of name corpus in `apply_features()` in chap6

### ISSUE THREAD

**Issue by alvations** [nltk/nltk_book#102]
The code section was giving the wrong usage of `apply_features` by accessing the name corpus as an array (from http://www.nltk.org/book/ch06.html). 

```
>>> from nltk.classify import apply_features
>>> train_set = apply_features(gender_features, names[500:])
>>> test_set = apply_features(gender_features, names[:500])
```

Should have been

```
>>> from nltk.classify import apply_features
>>> train_set = apply_features(gender_features, labeled_names[500:])
>>> test_set = apply_features(gender_features, labeled_names[:500])
```

For details, see http://stackoverflow.com/questions/28469476/typeerror-wordlistcorpusreader-object-has-no-attribute-getitem-while-us

**Comment by Amanda-Clark** [comment]
Already reported: https://github.com/nltk/nltk_book/issues/78
