### ISSUE TITLE
L for long integer no longer used in Python 3.X

### ISSUE THREAD

**Issue by dexedge** [nltk/nltk_book#105]
Exercise 2 in Chapter 1 states: 'That works out to 141167095653376L (the L at the end just indicates that this is Python's long-number format).'

As I understand it (I'm still new to Python), Python 3.X no longer has a "long" integer type, just a single integer type that can deal with arbitrarily long integers.

**Comment by stevenbird** [comment]
Thanks @dexedge. The fix will be deployed in the online book shortly.
