### ISSUE TITLE
Bug in lookup tagger code sample

### ISSUE THREAD

**Issue by drussellmrichie** [nltk/nltk_book#126]
The code sample is this:

> fd = nltk.FreqDist(brown.words(categories='news'))
> cfd = nltk.ConditionalFreqDist(brown.tagged_words(categories='news'))
> most_freq_words = fd.most_common(100)
> likely_tags = dict((word, cfd[word].max()) for word in most_freq_words)
> baseline_tagger = nltk.UnigramTagger(model=likely_tags)
> baseline_tagger.evaluate(brown_tagged_sents)

But this gives a ValueError at line 4, because word is not a word, but rather a (word, freq) tuple. The following fixes the issue.

> fd = nltk.FreqDist(brown.words(categories='news'))
> cfd = nltk.ConditionalFreqDist(brown.tagged_words(categories='news'))
> most_freq_words = fd.most_common(100)
> likely_tags = dict((word, cfd[word].max()) for word, _ in most_freq_words)
> baseline_tagger = nltk.UnigramTagger(model=likely_tags)
> baseline_tagger.evaluate(brown_tagged_sents)

**Comment by stevenbird** [comment]
Thanks @drussellmrichie
