### ISSUE TITLE
Different results for simple unigram tagger in Chap 5, section 4.3

### ISSUE THREAD

**Issue by drussellmrichie** [nltk/nltk_book#127]
In section 4.3 of Chapter 5, there is code for a simple tagger, and a figure of results for taggers of varying sizes. I ran that code (reproduced below), and got a [very different result](http://i.imgur.com/pgcIQeh.png). I am running NLTK 3.0.1 on Python 2.7. I know at least one other person is getting this issue, with NLTK 3.0.2 on Python 2 and Python 3.

    from nltk.corpus import brown
    import nltk

    def performance(cfd, wordlist):
        lt = dict((word, cfd[word].max()) for word in wordlist)
        baseline_tagger = nltk.UnigramTagger(model=lt, backoff=nltk.DefaultTagger('NN'))
        return baseline_tagger.evaluate(brown.tagged_sents(categories='news'))

    def display():
        import pylab
        words_by_freq = list(nltk.FreqDist(brown.words(categories='news')))
        cfd = nltk.ConditionalFreqDist(brown.tagged_words(categories='news'))
        sizes = 2 ** pylab.arange(15)
        perfs = [performance(cfd, words_by_freq[:size]) for size in sizes]
        pylab.plot(sizes, perfs, '-bo')
        pylab.title('Lookup Tagger Performance with Varying Model Size')
        pylab.xlabel('Model Size')
        pylab.ylabel('Perfdlormance')
        pylab.show()

    display()

**Comment by stevenbird** [comment]
@thanks @drussellmrichie – well spotted. I've updated the code.

Our FreqDist implementation no longer sorts items by decreasing frequency. So each of those models was using a random subset of the words, not the n most frequent words.
