### ISSUE TITLE
Using a Tagger: illustrate with Universal tagset?

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk_book#133]
It might lead to smoother exposition if we were to change the examples in Ch 5 Section 1 to use the universal tagset, and then later give more space to introducing and motivating the WSJ tagset.

**Comment by stevenbird** [comment]
I like this idea.

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk_book/commit/d672aa07756450e61cd1e3a8319815766a364167
