### ISSUE TITLE
map - Section 4.5 - subsection Higher-Order Functions

### ISSUE THREAD

**Issue by PeterHancox** [nltk/nltk_book#138]
1st map example isn't giving the same output in Python 3.4:

>>> lengths = map(len, nltk.corpus.brown.sents(categories='news'))
>>> sum(lengths) / len(lengths)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    sum(lengths) / len(lengths)
TypeError: object of type 'map' has no len()
>>> lengths = [len(sent) for sent in nltk.corpus.brown.sents(categories='news')]
>>> sum(lengths) / len(lengths)
21.75081116158339

**Comment by stevenbird** [comment]
Thanks @PeterHancox. We need to update that to start with:

```
lengths = list(map(len, nltk.corpus.brown.sents(categories='news')))
```

**Comment by stevenbird** [comment]
Deployed.
