### ISSUE TITLE
Exception raised by tagger.evaluate() example

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk_book#139]
```
File "/Users/ewan/git/nltk_book/book/ch06-2.doctest", line 718, in ch06-2.doctest
Failed example:
    print(tagger.evaluate(test_sents))
Exception raised:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest ch06-2.doctest[82]>", line 1, in <module>
        print(tagger.evaluate(test_sents))
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.2-py3.4.egg/nltk/tag/api.py", line 66, in evaluate
        test_tokens = sum(tagged_sents, [])
    TypeError: can only concatenate list (not "zip") to list
```

**Comment by dmollaaliod** [comment]
I have the same issue. The following override of TaggerI.evaluate(), based on /usr/lib/python3/dist-packages/nltk/tag/api.py seems to work for me:

from nltk.metrics import accuracy
from nltk.tag.util import untag
def evaluate(self,gold):
        "overriding evaluate from nltk.TaggerI, it seems to have a bug"
        tagged_sents = [list(s) for s in self.tag_sents(untag(sent) for sent in gold)]
        gold_tokens = sum(gold, [])
        test_tokens = sum(tagged_sents, [])
        return accuracy(gold_tokens, test_tokens)

**Comment by stevenbird** [comment]
The chapter 6 examples are very slow to run.

I tried to replicate the problem with a smaller example:

```
>>> from nltk.corpus import brown
>>> from nltk.data import load
>>> tagger = load('taggers/maxent_treebank_pos_tagger/english.pickle')
>>> tagged_sents = brown.tagged_sents(categories='news')
>>> size = int(len(tagged_sents) * 0.1)
>>> train_sents, test_sents = tagged_sents[size:], tagged_sents[:size]
>>> print(tagger.evaluate(test_sents))
0.6017617060732499
```

**Comment by stevenbird** [comment]
@dmollaaliod's solution is ok, but I'd like to replicate the problem, and then come up with a more space-efficient solution.
