### ISSUE TITLE
First draft of Sentiment Analysis section

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk_book#150]

**Comment by stevenbird** [comment]
The further work in https://github.com/nltk/nltk_book/commit/503aa83f98c5c1ef95c1e02f720209082aa3d05b looks good. It probably needs something about the components of a sentiment analysis system (the "pieces needed to solve it", cf https://github.com/nltk/nltk/wiki/Book-Development).

**Comment by ewan-klein** [comment]
I'm not sure there is any consensus or emerging best practice on what such components are. A souped-up lexicon-base system like VADER seems performs at a similar level -- at least on Twitter data --  and much faster compared to more sophisticated systems involving parsing and machine learning.
