### ISSUE TITLE
First draft of QA section

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk_book#151]

**Comment by stevenbird** [comment]
It looks like this is done in https://github.com/nltk/nltk_book/commit/532a6dd812c998b1dc2355b339be4570f74f9b56, https://github.com/nltk/nltk_book/commit/1e293a43c0d3fd57d1001a166e6ac5f9a0003b50, https://github.com/nltk/nltk_book/commit/0689ca611098b7e77c3bb445e4d1d0aa3bb609ab,
https://github.com/nltk/nltk_book/commit/a57c8ac0c5e79aa70dff35b7e54425d89f0ec4f2
