### ISSUE TITLE
Regex needs to be updated in example.

### ISSUE THREAD

**Issue by alvations** [nltk/nltk_book#168]
The regexes in [**NLTK's Regular Expression Tokenizer**](http://www.nltk.org/book/ch03.html) in Chapter 3 needs to be updated to suit the new `RexepTokenizer`. More details on nltk/nltk#1206

**Comment by pjhinton** [comment]
For those who run into this issued working through the examples via the online book, the relevant subsection is:

[NLTK's Regular Expression Tokenizer](http://www.nltk.org/book/ch03.html#nltk-s-regular-expression-tokenizer)

The broken code is:

```'That U.S.A. poster-print costs $12.40...'```

```
pattern = r'''(?x)    # set flag to allow verbose regexps
        ([A-Z]\.)+        # abbreviations, e.g. U.S.A.
        | \w+(-\w+)*        # words with optional internal hyphens
        | \$?\d+(\.\d+)?%?  # currency and percentages, e.g. $12.40, 82%
        | \.\.\.            # ellipsis
        | [][.,;"'?():-_`]  # these are separate tokens; includes ], [
'''
```

```nltk.regexp_tokenize(text, pattern)```

The erroneous result will look like:

```
[('', '', ''),
 ('S.', '', ''),
 ('', '', ''),
 ('', '-print', ''),
 ('', '', ''),
 ('', '', '.40'),
 ('', '', '')]
```

A revision that works for NLTK 3.4.5 on Python 3.7.4 is:

```python
from nltk.tokenize import RegexpTokenizer
```

```python
text = 'That U.S.A poster-print costs $12.40...'
```

```python
pattern = r'''(?x)
    (?:[A-Z]\.)+
    | \w+(?:-\w+)*
    | \$?\d+(?:\.\d+)?%?
    | \.\.\.
    | [][.,;"'?():-_`]
'''
```

```python
tokenizer = RegexpTokenizer(pattern)
```

```python
tokenizer.tokenize(text)
```

    ['That', 'U.S.', 'A', 'poster-print', 'costs', '$12.40', '...']

**Comment by stevenbird** [comment]
Thanks for this fix @pjhinton.
