### ISSUE TITLE
Chapter 1 exercise 24 typo

### ISSUE THREAD

**Issue by Boundarybreaker** [nltk/nltk_book#217]
Currently, Chapter 1's exercise 24 asks to find all the words ending in `ize` in text 6. However, text 6 is a Monty Python script, so it uses British spelling; `ize` doesn't ever appear in the document. It should be changed to `ise` instead so that it doesn't return an empty list.

**Comment by stevenbird** [comment]
Thanks @Boundarybreaker, and sorry for the delay
