### ISSUE TITLE
Add NLTK book and other documentation to PyPI package

### ISSUE THREAD

**Issue by donpellegrino** [nltk/nltk_book#219]
The current nltk package on PyPI does not seem to install any documentation for NLTK. It would be great if the documentation and NLTK Book could be included in the PyPI package for use on systems that do not have constant Internet access. The NLTK Book might be installed into /share/doc/nltk within a venv having the nltk package installed.

**Comment by stevenbird** [comment]
Yes, nice to have, but no capacity to do this, sorry
