### ISSUE TITLE
Racial Slur in Chapter 7.2.5

### ISSUE THREAD

**Issue by hLuo27** [nltk/nltk_book#264]
Highly offensive and inappropriate language: https://www.nltk.org/book/ch07.html

**Comment by HadziJo** [comment]
Adding a section or paragraph number to your observation would be a great help to others attempting to address the issue, Though providing a search string would (use wild card characters for the offensive bits) would be very helpful.

**Comment by tomaarsen** [comment]
I believe they are referring to section 2.5.

**Comment by stevenbird** [comment]
The chunk/chink terminology goes back at least 30 years (e.g. Liberman and Church 1992). The words are not used in the context of discussion of race, and there is no reasonable reading of this term as a racist slur in this context.

Liberman, Mark Y., and Kenneth W. Church. "Text analysis and word pronunciation in text-to-speech synthesis." Advances in speech signal processing (1992): 791-831.
