### ISSUE TITLE
Incorrect variable name in Chapter 6, section 1.2

### ISSUE THREAD

**Issue by davechallis** [nltk/nltk_book#78]
Some code in chapter 6, section 1.2 should use the variable 'labelled_names' instead of 'names' in two places:

    >>> featuresets = [(gender_features2(n), gender) for (n, gender) in names]

should be:

    >>> featuresets = [(gender_features2(n), gender) for (n, gender) in labelled_names]

And below that:

    >>> train_names = names[1500:]
    >>> devtest_names = names[500:1500]
    >>> test_names = names[:500]

should read:

    >>> train_names = labelled_names[1500:]
    >>> devtest_names = labelled_names[500:1500]
    >>> test_names = labelled_names[:500]

'names' is loaded with `from nltk.corpus import names`, which is of type `<class 'nltk.corpus.util.LazyCorpusLoader'>`, which isn't iterable.

**Comment by ewan-klein** [comment]
Fixed in 6c04d2b
